/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package packet

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object RequestAuthLogin extends ThriftStructCodec3[RequestAuthLogin] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("RequestAuthLogin")
  val LoginField = new TField("login", TType.STRING, 1)
  val LoginFieldManifest = implicitly[Manifest[String]]
  val PasswordField = new TField("password", TType.STRING, 2)
  val PasswordFieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      LoginField,
      false,
      false,
      LoginFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      PasswordField,
      false,
      false,
      PasswordFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: RequestAuthLogin): Unit = {
  }

  def withoutPassthroughFields(original: RequestAuthLogin): RequestAuthLogin =
    new Immutable(
      login =
        {
          val field = original.login
          field
        },
      password =
        {
          val field = original.password
          field
        }
    )

  override def encode(_item: RequestAuthLogin, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): RequestAuthLogin = {

    var loginOffset: Int = -1
    var passwordOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                loginOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'login' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                passwordOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'password' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      loginOffset,
      passwordOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): RequestAuthLogin =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): RequestAuthLogin = {
    var login: String = null
    var password: String = null
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                login = readLoginValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'login' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                password = readPasswordValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'password' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      login,
      password,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    login: String,
    password: String
  ): RequestAuthLogin =
    new Immutable(
      login,
      password
    )

  def unapply(_item: RequestAuthLogin): _root_.scala.Option[scala.Product2[String, String]] = _root_.scala.Some(_item)


  @inline private def readLoginValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeLoginField(login_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(LoginField)
    writeLoginValue(login_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeLoginValue(login_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(login_item)
  }

  @inline private def readPasswordValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writePasswordField(password_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PasswordField)
    writePasswordValue(password_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePasswordValue(password_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(password_item)
  }


  object Immutable extends ThriftStructCodec3[RequestAuthLogin] {
    override def encode(_item: RequestAuthLogin, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): RequestAuthLogin = RequestAuthLogin.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[RequestAuthLogin] = RequestAuthLogin.metaData
  }

  /**
   * The default read-only implementation of RequestAuthLogin.  You typically should not need to
   * directly reference this class; instead, use the RequestAuthLogin.apply method to construct
   * new instances.
   */
  class Immutable(
      val login: String,
      val password: String,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends RequestAuthLogin {
    def this(
      login: String,
      password: String
    ) = this(
      login,
      password,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      loginOffset: Int,
      passwordOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends RequestAuthLogin {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val login: String =
      if (loginOffset == -1)
        null
      else {
        _proto.decodeString(_buf, loginOffset)
      }
    lazy val password: String =
      if (passwordOffset == -1)
        null
      else {
        _proto.decodeString(_buf, passwordOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the RequestAuthLogin trait with additional state or
   * behavior and implement the read-only methods from RequestAuthLogin using an underlying
   * instance.
   */
  trait Proxy extends RequestAuthLogin {
    protected def _underlying_RequestAuthLogin: RequestAuthLogin
    override def login: String = _underlying_RequestAuthLogin.login
    override def password: String = _underlying_RequestAuthLogin.password
    override def _passthroughFields = _underlying_RequestAuthLogin._passthroughFields
  }
}

trait RequestAuthLogin
  extends ThriftStruct
  with scala.Product2[String, String]
  with java.io.Serializable
{
  import RequestAuthLogin._

  def login: String
  def password: String

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = login
  def _2 = password


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (login ne null) {
                writeLoginValue(login, _oprot)
                _root_.scala.Some(RequestAuthLogin.LoginField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (password ne null) {
                writePasswordValue(password, _oprot)
                _root_.scala.Some(RequestAuthLogin.PasswordField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): RequestAuthLogin = {
    var login: String = this.login
    var password: String = this.password
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        login = readLoginValue(_blob.read)
      case 2 =>
        password = readPasswordValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      login,
      password,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): RequestAuthLogin = {
    var login: String = this.login
    var password: String = this.password

    _fieldId match {
      case 1 =>
        login = null
      case 2 =>
        password = null
      case _ =>
    }
    new Immutable(
      login,
      password,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetLogin: RequestAuthLogin = unsetField(1)

  def unsetPassword: RequestAuthLogin = unsetField(2)


  override def write(_oprot: TProtocol): Unit = {
    RequestAuthLogin.validate(this)
    _oprot.writeStructBegin(Struct)
    if (login ne null) writeLoginField(login, _oprot)
    if (password ne null) writePasswordField(password, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    login: String = this.login,
    password: String = this.password,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): RequestAuthLogin =
    new Immutable(
      login,
      password,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[RequestAuthLogin]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[RequestAuthLogin]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.login
    case 1 => this.password
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "RequestAuthLogin"
}